### ISSUE TITLE
ng5-slider-pointer moving on browser zoom

### ISSUE THREAD

**Issue by nagarjunanarni** [angular-slider/ngx-slider#104]
Hi,
   i am using ng5 slider to display min max slider. on page load slider was displaying with gap on right side max value. when i zoom in or zoom out the browser window, the bar was filling correctly with max value. not sure why it is happening. here the max value is 2020. Can someone help me to fix the issue please.
<img width="198" alt="Capture" src="https://user-images.githubusercontent.com/51341232/58833103-955b5b80-860d-11e9-8116-fb428505dcc1.PNG">

**Comment by piotrdz** [comment]
Can you post the exact slider options you are using? Or preferably, if you can, provide a full StackBlitz example (for example by forking [this example](https://stackblitz.com/edit/ng5-slider-range-slider-example)).

**Comment by piotrdz** [comment]
Closing old stale issues without more information.
