### ISSUE TITLE
Don't animate the handle while dragging

### ISSUE THREAD

**Issue by ValentinH** [angular-slider/ngx-slider#114]
I've noticed that when dragging the slider on phone, it feels laggy. This is because of the animation that slows it down.

The animation should be disabled while the user is dragging the slider. On `angularjs-slider`, I simply did it by applying a specific class (https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.less#L21) during the drag event.

**Comment by piotrdz** [comment]
Thanks, that's a good idea. I'll do this.

**Comment by adgrace** [comment]
Is there an option to disable the animation entirely? If not please could this be added along with disabling on mobile

**Comment by gcherem** [comment]
Any update on this issue? I need this too

**Comment by ValentinH** [comment]
I would actually be a good opportunity to contribute to this project. I can review it if needed :)

**Comment by easycheese** [comment]
https://angular-slider.github.io/ng5-slider/docs/classes/_options_.options.html#animate

Animations can be turned off here.

**Comment by ValentinH** [comment]
Is this still under your radar @piotrdz ?

**Comment by piotrdz** [comment]
Yes, I am just going slowly through the tickets.

I disabled the animation on move by default, but I also added an option `animateOnMove` to enable the old behaviour if desired.

Pushed to master, awaiting next release.

**Comment by piotrdz** [comment]
Released in v2.0.1. Closing.
