### ISSUE TITLE
Rxjs dependencies

### ISSUE THREAD

**Issue by Enngage** [angular-slider/ngx-slider#117]
Hi, 

I like your library, but I would like it so much more if you removed the `rxjs-compat` dependency as well as `rxjs` on version 5. 

Can you migrate to `rxjs` 6?

**Comment by piotrdz** [comment]
Not without dropping Angular 5 support. I intend to keep the compatibility if possible.

If I do decide to move to rxjs 6, then the project will likely need a new name, too :)

**Comment by Enngage** [comment]
I don't think there is any point in supporting Angular 5 since 8 is already out. The big problem with having old rxjs is that you basically force anyone using your library to include whole rxjs which increases build size quite significantly. Its a deal breaker imho.

**Comment by Enngage** [comment]
Following is an image from `webpack-bundle-analyzer` where you can see that your library is exporting **full rxjs** package which is adding `168.9 KB` to bundle size. Size of your code is another `46 KB`.

Since this is an angular plugin, you should not include rxjs in package dependencies, but rather define it as a `peerDependency`. 

![ng5-slider](https://user-images.githubusercontent.com/7137351/60658344-42b2d080-9e53-11e9-991b-7edaa036b40c.png)

**Comment by piotrdz** [comment]
I really don't want to drop the Angular 5 support or maintain different branches for different Angular versions at this stage.

The good news is that I found a workable compromise. I changed the version specifier for rxjs to be `>=5.5.6`. On Angular 5, it will use rxjs 5 and on Angular 6+ it will work with rxjs 6. `rxjs-compat` has to stay as a dependency, but it is a very small package, so it shouldn't be a problem. 

This will be available in next slider release.

**Comment by Enngage** [comment]
But users wanting to use it with Angular 5 can use older versions, right? I really don't see how forcing anyone using your library to include full `rxjs-compat` dependency is a good idea. `122KB` is not "very small package" - its quite significant and it is also reason we decided not to use this package :/

**Comment by rathodsanjay** [comment]
Hi @piotrdz any updates on when the new version is going to be released?

I have used ng5-slider in one of my projects and I have to do a workaround in the package.json to avoid rxjs version conflicts between modules.

**Comment by stefanobranco** [comment]
Thanks for the workaround, that's the biggest issue dealt with already.

Personally, I can only sign what @Enngage has mentioned already. Official Angular 5 support has ended - in fact, Angular 6 support will be ending in November this year. As with other packages, people with old and unsupported angular versions can always use older versions of your package as well, can't they?

**Comment by deniskaber** [comment]
Hi there! Any news on this issue?

**Comment by deniskaber** [comment]
Meanwhile you can use the following workaround:

Add this to your `tsconfig.json`
```
"paths": {
    "rxjs": [
        "../node_modules/rxjs"
    ],
    "rxjs/*": [
        "../node_modules/rxjs/*"
    ]
}
```

**Comment by merobal** [comment]
@piotrdz your update for the rxjs dep is not yet released, however Ivy is coming soon and that doesn't like rxjs 5: https://github.com/angular-slider/ng5-slider/issues/159

**Comment by john-melin** [comment]
Having it working with ng5 does not require you to use the whole rxjs package as a dependency, it will still work with a peerDependency

**Comment by ckelley7** [comment]
The dependency on rxjs 5 broke my angular 9 build and the above tsconfig.json workaround didn't work.   So, I fell back to a jquery slider.

**Comment by merobal** [comment]
I just found this now via Google search: https://github.com/m0t0r/ngx-slider

**Comment by ckelley7** [comment]
> I just found this now via Google search: https://github.com/m0t0r/ngx-slider

Thank you!  I'll give it a try.

**Comment by piotrdz** [comment]
I have posted updates about this in other places, but this is the original ticket, so I should add it here as well:

v2.0 of slider targeting Angular 6+ and rxjs 6+ is in preparation and will be released very soon.

**Comment by piotrdz** [comment]
Release v2.0.0 is out. Closing.
