### ISSUE TITLE
Reverse label and slider

### ISSUE THREAD

**Issue by zerdoun** [angular-slider/ngx-slider#120]
Hi,

I would like to know if there is a way to reverse the labels and the slider in order to have the labels below the slider.

Thanks a lot :)

**Comment by DoimoInterlogica** [comment]
I managed to do it. This is the SCSS.
Adjust the values according to your style.

.ngx-slider {
    margin-top: 70px;
    .ngx-slider-bar-wrapper {
        margin-top: -80px !important;
    }
    .ngx-slider-pointer {
        margin-top: -64px !important;
    }
}

**Comment by zerdoun** [comment]
@DoimoInterlogica Thanks a lot for your help !!
