### ISSUE TITLE
Version "^1.2.1" breaks slider. 

### ISSUE THREAD

**Issue by tcoz** [angular-slider/ngx-slider#121]
It looks like we're at 1.2.4 now, which is what our package lock indicated. Somewhere after 1.2.1, the slider breaks. When you click on a slider handle, you drag, and it only moves to the point on the handle you clicked on (so a few pixels this or that way). It otherwise does not continue to drag. 

Locking the version to 1.2.1 fixed it. Again, not exactly sure when this emerged, but definitely after 1.2.1.

**Comment by piotrdz** [comment]
There are a few tickets open for the same problem - see #144 and #111. Closing this one.
