### ISSUE TITLE
rxjs Observable 

### ISSUE THREAD

**Issue by krishnaraghavendra** [angular-slider/ngx-slider#123]
Hi, 

I have "rxjs": "6.5.2",  "rxjs-compat": "6.5.2",  dependencies in my project, when i add  "ng5-slider": "^1.2.4" and build the project I am getting an error as below

 Type 'import("node_modules/rxjs/internal/Observable<any>”).Observable' is not assignable to type 'import("node_modules/rxjs/Observable").Observable<any>
  Property 'buffer' is missing in type 'Observable<any>'.

**Comment by piotrdz** [comment]
I assume this is fixed with recent changes in v2.0.0 with upgrade to rxjs >= 6, so I will close.

If it is still a problem, please re-open.
