### ISSUE TITLE
Entering the value out of the range (0 - 100) via keyboard for slider which having step property

### ISSUE THREAD

**Issue by adityawader** [angular-slider/ngx-slider#124]
Hello,
I am using slider with step (step = "10"). When I provide the value (via keyboard) that is out of the range (0 - 100), and then I try entering allowed value(0 - 100), slider doesn't reflect this change, and stays freezes.
Thank you

**Comment by piotrdz** [comment]
By default, the slider is enforcing the value constraints (`value` and `highValue` in range of `floor` to `ceil` and `value` < `highValue`).

If this is causing problems, it can be disabled by setting `enforceRange: false` in slider options.

**Comment by piotrdz** [comment]
Closing old stale issues without more information.
