### ISSUE TITLE
How we can show year value in position top? 

### ISSUE THREAD

**Issue by rahulpathak** [angular-slider/ngx-slider#125]
I want to use slider like this, how we can show month value in top ? 
same like Date, Year, Month.

![image](https://user-images.githubusercontent.com/2330971/61397671-074ee200-a8e8-11e9-8bb2-923a3aa4f400.png)

![image](https://user-images.githubusercontent.com/2330971/61397781-441ad900-a8e8-11e9-83d6-e1cff18f896a.png)

![image](https://user-images.githubusercontent.com/2330971/61397816-55fc7c00-a8e8-11e9-8b53-d770cce7f03b.png)

**Comment by AskmeKolaric** [comment]
https://angular-slider.github.io/ng5-slider/demos   find - Slider with dates and you can easily set it up.

**Comment by piotrdz** [comment]
As answered above, the trick is to use ticksArray with the desired range, or a custom translate function. Closing as answered.
