### ISSUE TITLE
IE, FireFox bug tooltip, legend and ticks all the way to the left. 

### ISSUE THREAD

**Issue by glennovische** [angular-slider/ngx-slider#126]
Broken view:
![image](https://user-images.githubusercontent.com/12197998/61446227-2af94300-a94f-11e9-914f-828f86918651.png)

When opening in IE the slider is not displayed correctly, when resizing the screen it's getting fixed. 

Correct view after resizing or other browser.
![image](https://user-images.githubusercontent.com/12197998/61446129-fa190e00-a94e-11e9-97c5-c3ee64321f85.png)

More info:
The slider is in an accordion that's initially hidden, after opening it the slider is not showed correctly first screenshot. The styling on the elements is "transform: translateX(0px);" for some reason.

After selecting another accordion and switching back the slider is showed correctly again and the transform: translateX also gets the right pixel value. This bug is in Firefox and in IE

**Comment by vortaxg** [comment]
have the same issue, but it reproduces only in Chrome(current version 76)
in IE it works as expected

**Comment by glennovische** [comment]
This can be fixed using a window resize when opening the tab where the slider is present. Would like to see a fix by the developers of this slider tho

**Comment by vortaxg** [comment]
it would be great

**Comment by piotrdz** [comment]
This is a known limitation of some browser versions. Please refer to [the documentation about it](https://github.com/angular-slider/ngx-slider/blob/master/KNOWN_ISSUES.md#slider-is-not-refreshing-when-used-in-a-dynamic-component) and use `manualRefresh` if necessary.
