### ISSUE TITLE
HighValue handle doesn't have bound events on model change

### ISSUE THREAD

**Issue by pegans** [angular-slider/ngx-slider#132]
Hi,

I am trying to conditionally change the slider from single value to range value. For that purpose I initially set the highValue to null and this gives me the single value slider. When I tried: setTimeout( () => highValue = somevalue, 1000 );, the component would render the high value handle but it can't be moved because the events are not bound to it.
This is my example:
HTML:
`<ng5-slider [(value)]="value" [(highValue)]="highValue" [options]="options"></ng5-slider>`
TS:
```
export class SimpleSliderComponent {
  value: number = 100;
  highValue: number = null;
  options: Options = {
    floor: 0,
    ceil: 250
  };

  constructor() {
    setTimeout(()=> {
      this.highValue = 155;
    }, 1000);
  }
}
```
After some investigation on a downloaded source I could fix the issue by calling resetSlider() inside applyInputModelChange() method. Hope this helps.

**Comment by piotrdz** [comment]
> After some investigation on a downloaded source I could fix the issue by calling resetSlider() inside applyInputModelChange() method.

This is the only supported way to do it.

Changing slider from single value to range dynamically through changing `highValue` is not supported and there are no plans to support it.
