### ISSUE TITLE
Question: Floor/Ceil Labels

### ISSUE THREAD

**Issue by scottctr** [angular-slider/ngx-slider#136]
Is it possible to NOT show labels for the floor and ceil values? ....or to position them horizontal to the bar?

Would also be great if there was a way to a custom max level below the bar.

Here's what I'm trying to create:
![image](https://user-images.githubusercontent.com/29161665/63122305-fbe4ea00-bf6b-11e9-8028-3ba781095085.png)

**Comment by scottctr** [comment]
Figured out how to hide the floor/ceil labels:
    translate: (value: number, label: LabelType): string => {
      switch (label) {
        case LabelType.Low:
          return '<b>Min price:</b> $' + value;
        case LabelType.High:
          return '<b>Max price:</b> $' + value;
        default:
          _**return '';**_
      }

**Comment by piotrdz** [comment]
Closing as answered.

**Comment by carlos-sardina** [comment]
> Figured out how to hide the floor/ceil labels:
> translate: (value: number, label: LabelType): string => {
> switch (label) {
> case LabelType.Low:
> return 'Min price: $' + value;
> case LabelType.High:
> return 'Max price: $' + value;
> default:
> _**return '';**_
> }

This works! Thanks
