### ISSUE TITLE
ng5-builder issue in Edge browser

### ISSUE THREAD

**Issue by shakibamor** [angular-slider/ngx-slider#141]
I am using ng5-slider. It is working totally fine on Chrome but it goes outside modal window in Edge. Please help.

![image](https://user-images.githubusercontent.com/8889578/64045643-ca594a80-cb37-11e9-9c3d-f10cf0c6bbce.png)

**Comment by piotrdz** [comment]
Closing old issues related to old versions of slider. Also, issues related to old Edge browser versions should not be relevant today.
