### ISSUE TITLE
Only react to click/drag events on pointer (instead of full bar)

### ISSUE THREAD

**Issue by schacki** [angular-slider/ngx-slider#142]
I have a srollable screen with mulitple sliders placed on it. So especially on touch devices, when a user trys to scroll, it is almot impossible, without changing the sliders.

Is it possible, that only the pointer reacts to click, drag or touch events instead of the complete bar?

**Comment by gregoryfikator** [comment]
Try this option:

`onlyBindHandles: true`

**Comment by schacki** [comment]
Thanks a lot, works perfect.

Is this documented somewhere?

**Comment by gregoryfikator** [comment]
No problem. I also had such problem but found this
https://angular-slider.github.io/ng5-slider/docs/classes/_options_.options.html#onlybindhandles

**Comment by piotrdz** [comment]
Closing as this is answered.
