### ISSUE TITLE
Cannot read property 'toString' of undefined in slider component.

### ISSUE THREAD

**Issue by jegius** [angular-slider/ngx-slider#148]
Hello, i have a problem with your slider in my project. 

![image](https://user-images.githubusercontent.com/11362702/65705661-f49c1a80-e099-11e9-887a-52684e96aadb.png)

Can you add truety check in this place? 

![image](https://user-images.githubusercontent.com/11362702/65705874-4f357680-e09a-11e9-9a60-f8c563b75064.png)

It's in SliderComponent.

Thank you.

**Comment by piotrdz** [comment]
All of the values used in this function should be well-defined. It must be something to do with how you set up your slider.

Can you provide a minimum reproduction? A StackBlitz example would be ideal.

**Comment by piotrdz** [comment]
Closing old stale issues without more information.
