### ISSUE TITLE
Setting disable post-render, does not work

### ISSUE THREAD

**Issue by pauloosthuysen** [angular-slider/ngx-slider#151]
When the component is fully rendered and you set `disabled: true` under options, the component still stays active.

**Comment by pauloosthuysen** [comment]
I have fixed and submitted a pull request for this: https://github.com/angular-slider/ng5-slider/pull/152

**Comment by tedp** [comment]
@pauloosthuysen responses don't seem forthcoming for this project.  I wonder why?

**Comment by pauloosthuysen** [comment]
@tedp yeah, I also find it weird, for such a popular component...

**Comment by piotrdz** [comment]
@pauloosthuysen  @tedp A bad year is a bad year for the sole maintainer.

I am starting to work on the slider again, but won't get to fix everything right away. I will mark this for post-v2 work.

**Comment by pauloosthuysen** [comment]
@piotrdz sorry to hear, all of the best.

**Comment by piotrdz** [comment]
Now that v2 is out, I went back to this issue, but I don't see anything to fix here. [This official example](https://angular-slider.github.io/ngx-slider/demos#disabled-slider) demonstrates how to apply a change to options object and disabling works as expected. I am going to close this.
