### ISSUE TITLE
Unable to update options data after some function calls

### ISSUE THREAD

**Issue by nagaraju123** [angular-slider/ngx-slider#157]
The values for the slider i have setted first time it is setting fine.
When i am trying to update options ceil and floor values it is not working.

**Comment by mKay00** [comment]
Same issue as #176 and the same [workaround](https://github.com/angular-slider/ng5-slider/issues/176#issuecomment-642811483) works.
Options can't be changed after the slider has been initialized. The whole Options object has to be replaced with a new object e.g.
this.options = { ...}

**Comment by piotrdz** [comment]
Closing as answered.
