### ISSUE TITLE
left bar color, different from rright bar color (when only using value => no highvalue)

### ISSUE THREAD

**Issue by HansVanderGucht** [angular-slider/ngx-slider#160]
I would like to have a different color left from the value. Then the color on the right.
I'm not using the highvalue ( only for selecting 1 value)

**Comment by piotrdz** [comment]
You can do it by showing selection bar and applying custom styling. See [this Stackblitz example](https://stackblitz.com/edit/ng5-slider-issue-160?file=src/app/app.component.scss).
