### ISSUE TITLE
Question: Is it possible to stop values switching when highValue less than minValue?

### ISSUE THREAD

**Issue by SMH110** [angular-slider/ngx-slider#165]
Hello,
I am uisng the range slider with two HTML input fields, where slider's value and slider's highValue can be controlled by those HTML inputs.
When a user set the min value of the slider using the HTML input associated with slider's value, then tryies to set the highValue of the slider using the HTML input associated with slider's highValue the values of the slider switches over.
I was wondering if there's an option to stop this behaviour.

[See demo on StackBlitz](https://stackblitz.com/edit/ng5-slider-range-slider-example-crymqp)

**Comment by piotrdz** [comment]
No, this is not currently supported - see issue #94.

I have a direction for the future, though - adding support for multiple generic slider handles, without range between them - issue #115.

I will close this in favour of #115.
