### ISSUE TITLE
Add a class for the selected tick

### ISSUE THREAD

**Issue by dana-c0914** [angular-slider/ngx-slider#169]
Hi,

I am looking to style the legend of the currently selected tick/value. I saw that the knowledge whether the tick is selected or not is available in the code so it would be nice to have at least a class on the `ng5-slider-tick` element to show which one is active that we could use for styling.

Thanks in advance

**Comment by piotrdz** [comment]
This is already present - class `ngx-slider-selected` (`ng5-slider-selected` before v2.0.0) is applied to the selected tick element.

For an example in action, see [this demo](https://angular-slider.github.io/ngx-slider/demos#ticks-values-range-slider).
