### ISSUE TITLE
The maxRange value can't be updated dynamically

### ISSUE THREAD

**Issue by gabrielnemeth** [angular-slider/ngx-slider#171]
I've problem setting the `maxRange` dynamically.
Stackblitz simple [example](https://stackblitz.com/edit/angular-yuuxxe).

In my real app, I need to set up the `maxRange` based on `value` parameter's value. So if it changes over time, I need to update also the `maxRange`, e.g. further the user drags the first handle, the `maxRange` should be larger.

Any idea how to achieve this?

**Comment by xCryzed** [comment]
Hey we have the same problem, send help :)

**Comment by tcernera** [comment]
export class AppComponent  {
  manualRefresh: EventEmitter<void> = new EventEmitter();
  value: number = 40;
  highValue: number = 100;
  options: Options = {
    floor: 0,
    ceil: 1000,
    step: 10,
    minRange: 60,
    maxRange: null,
    pushRange: true,
    enforceStep: false,
    animate: false,
  };

  setNewMaxRange(val: number) {
    const newOptions: Options = Object.assign({}, this.options);
    newOptions.maxRange = val;
    this.options = newOptions;
    this.manualRefresh.emit();
  }
}

You need to set new options in the following manner.  Link to the documentation for further reading. https://angular-slider.github.io/ng5-slider/demos#dynamic-options-slider

**Comment by piotrdz** [comment]
Above answer is correct, passing new options should be done by creating a new object.
