### ISSUE TITLE
[BUG] Not able to slide from slider-pointers in latest(1.2.4) version

### ISSUE THREAD

**Issue by fzs1994** [angular-slider/ngx-slider#173]
I'm not able to change start and end time by sliding from slider-pointers. However, I can change by clicking ticks in the range. I have checked that, it is working fine in earlier version(1.2.0). This specifically happens when there are multiple sliders generated in loop from .ts JSON data.

Here is the [StackBlitz](https://stackblitz.com/edit/ng5-slider-range-slider-dynamic-ceil-example-o2lvdn)

Maybe reference to [this issue](https://github.com/angular-slider/ng5-slider/issues/121) also.

**Comment by piotrdz** [comment]
There are a few tickets open for the same problem - see #144 and #111. Closing this one.
