### ISSUE TITLE
How to set dynamically floor/ ceil value.

### ISSUE THREAD

**Issue by ArqamRafay** [angular-slider/ngx-slider#176]
I try this but not work 
HTML:
   <ng5-slider [(value)]="value" [(highValue)]="highValue" [options]="options" [manualRefresh]="manualRefresh"></ng5-slider>

Ts:
  manualRefresh: EventEmitter<void> = new EventEmitter();
  value: number = 0;
  highValue: number = 0;
  options: Options = {
    floor: 0,
    ceil: 500,
    animate: true,
  };
setNewMaxRange(maxVal: number) {
this.options.floor= 0;
this.options.ceil= maxVal;
    this.manualRefresh.emit();
  }

**Comment by jawadahm** [comment]
I had a similar issue and I made this working as:

let opts: Options = {
        floor: this.min,
        ceil: this.max,
        getPointerColor: ()=>{return 'gray'},
        getSelectionBarColor: () => {return 'gray'}
      };

      this.options = opts;

This worked for me.

**Comment by piotrdz** [comment]
As answered above, setting new options is done by creating a new options object.

**Comment by indrasaswita** [comment]
> I had a similar issue and I made this working as:
> 
> let opts: Options = {
> floor: this.min,
> ceil: this.max,
> getPointerColor: ()=>{return 'gray'},
> getSelectionBarColor: () => {return 'gray'}
> };
> 
> ```
>   this.options = opts;
> ```
> 
> This worked for me.

But it was only worked once. Is there any way to do it repeatedly?
Thanks
