### ISSUE TITLE
ERROR Error: Expecting instance of DOM Element

### ISSUE THREAD

**Issue by santosh2221994** [angular-slider/ngx-slider#179]
'<ng5-slider [(value)]="value" [(highValue)]="highValue" [options]="options">
            </ng5-slider>'
'value: number = 40
  highValue: number = 60
  options: Options = {
    floor: 0,
    ceil: 100
  }'

**Comment by SpiegelSoft** [comment]
Did you find the cause of this bug?

**Comment by Matthi0uw** [comment]
Any solution ?

**Comment by shisho585** [comment]
Maybe it's because you didn't put the end tag?

**Comment by piotrdz** [comment]
I assume this is a duplicate of #195.
