### ISSUE TITLE
tickStep interpreted as array of tick positions and crash on no input

### ISSUE THREAD

**Issue by jfoxworth** [angular-slider/ngx-slider#186]
I was using an input to allow users to input a desired tick step, and then feeding that value into the "tickStep" option parameter for the slider. What I found was that this value was often used as a singular position where a tick was placed - as if it was being interpreted as an array of tick positions. Not sure if this was because the step given may have been a string instead of a number.

Along the same lines, when the user is editing that input and deletes the current value for the tickstep, the browser tab crashes. It seems as if the algorithm is trying to divide by a null somewhere? 

Unfortunately, I had to remove this option as it was very unstable due to these reasons.

**Comment by piotrdz** [comment]
Sorry, I am not going to add validation for all options object values. You should do your own validation for the inputs you are supplying.
