### ISSUE TITLE
Ng-Slider min value and current selected value setting NaN upon refresh browser

### ISSUE THREAD

**Issue by abhijitbanke** [angular-slider/ngx-slider#187]
@piotrdz 
@rzajac 
@ValentinH 
@jhinzmann 

Slider min value and current selected value setting NaN upon refresh browser . 
Even input value and min value assigned in ngOnInIt function.

**Ng5-Slider version : 1.2.4**

e.g Code snippet
#HTML Code
``````
<input type="text" class="form-control range-field" (blur)="tbupdate(0)"
		[(ngModel)]="budgetIncomeDto.myIncome" placeholder="My Income" name="pemi.highValue" /> 
<ng5-slider [(value)]="budgetIncomeDto.myIncome" [options]="poptions" (userChangeEnd)="update()"></ng5-slider>
```


#TypeScript code
 ngOnInit() {
  #Service Call
  this.getBudgetIncomeDtoByApplicationUser();
 }
 
 
 public getBudgetIncomeDtoByApplicationUser() {
    this.budgetIncomeDtoService.getBudgetIncomeDtoByApplicationUser().subscribe((res: any) => {
      this.budgetIncomeDto = res
      this.ref.detectChanges();
      console.log("getBudgetIncomeDtoByApplicationUser", res)
    });
  }

**Comment by shisho585** [comment]
There is no full example of the code here, but I think the problem is that.
you put the data in the variables only after they return from subscribe(), so when the component loads, does not have the data yet and therefore an error returns.

**Comment by piotrdz** [comment]
Yes, as answered above, you need to ensure that the value you are binding to is valid. This is not the responsibility of the slider.
