### ISSUE TITLE
Is it possible to customize slider speed?

### ISSUE THREAD

**Issue by asemchenko** [angular-slider/ngx-slider#188]
Hi!

I have founded this library, and it is really cool. But in my case, I need an ability to move slider fastly then default speed. Can you help me to find out how to do this? Does this library support this customization feature?

**Comment by manu2495** [comment]
no answer yet ? I really would like this feature

**Comment by dar097** [comment]
`.ng5-slider.animate .ng5-slider-pointer{
    transition: all 0.3s linear;
}`

That is what is applied when animate is on, however for me it wasn't always working, so I added a class to the ng5-slider component myself and changed the .animate part to reflect it.

By changing the transition value, you can have a different animation.

**Comment by piotrdz** [comment]
As answered above, you can change the transition time for animation.

Note also that as of v2.0.1, animation on moving slider is disabled by default (controlled by option `animateOnMove`).

And if you want a faster reaction time to changing inputs, you can change the throttling time options: `mouseEventsInterval`, `touchEventsInterval`, `inputEventsInterval`, `outputEventsInterval`.
