### ISSUE TITLE
Can add @least 2... ng5-slider in same component

### ISSUE THREAD

**Issue by kavigithub** [angular-slider/ngx-slider#206]
hello,

Is there any option to create more than 1, ng5 slider in the same component. 
As i tried with the different formGroupName but when i drag the first slider...second slider automatically drag itself.

Can anyone please help me out

this is the code.... 
1st option i tried...
html
<div class="col-md-6 form-input-block mt-2">
                  <label for="maxAmt">Days on the platform</label>
                  <div class="custom-slider">
                    <ng5-slider formControlName="daysOptions" [(value)]="value" [(highValue)]="highValue" [options]="options"></ng5-slider>
                  </div>
                </div>

                <div class="col-md-6 form-input-block mt-2">
                  <label for="maxAmt">Rate Between</label>
                  <div class="custom-slider">
                    <ng5-slider formControlName="rateOptions" [(value)]="value" [(highValue)]="highValue" [options]="options"></ng5-slider>
                  </div>
                </div>

.ts file

import { Options } from 'ng5-slider';
options: Options = {
    floor: 0,
    ceil: 50,
    step: 1,
    showTicks: false
  };

and add the formControls in my fb.group
----------------------------------------------------------------------------------------------------------------------------------------
2nd I tried for
html
html
<div class="col-md-6 form-input-block mt-2">
                  <label for="maxAmt">Days on the platform</label>
                  <div class="custom-slider">
                    <ng5-slider  [(value)]="value" [(highValue)]="highValue" [options]="options1"></ng5-slider>
                  </div>
                </div>

                <div class="col-md-6 form-input-block mt-2">
                  <label for="maxAmt">Rate Between</label>
                  <div class="custom-slider">
                    <ng5-slider [(value)]="value" [(highValue)]="highValue" [options]="options2"></ng5-slider>
                  </div>
                </div>

.ts file
 options1: Options = {
    floor: 0,
    ceil: 50,
    step: 1,
    showTicks: false
  };

 options2: Options = {
    floor: 0,
    ceil: 100,
    step: 1,
    showTicks: false
  };

Could you please help me out . Let me know if this is gonna work or not.
Thanks

**Comment by piotrdz** [comment]
In the first instance of the component, you are using both reactive form bindings `formControlValue` and non-reactive bindings for `value` and `highValue`. This is wrong, you should use either the reactive style ones, or the non-reactive ones.

In your second instance, you are using non-reactive binding, and binding to the very same `value` and `highValue` targets. So no wonder you are seeing both sliders change at the same time.
