### ISSUE TITLE
Warning when running npm install

### ISSUE THREAD

**Issue by ThomasDevens** [angular-slider/ngx-slider#221]
Getting this warning after running npm install when running ngcc post-install (Angular v9.1.4, node v12.18.4)

Warning: Unable to fully load {path_to_project}/node_modules/@angular-slider/ngx-slider/bundles/angular-slider-ngx-slider.umd.js for source-map flattening: The "path" argument must be of type string. Received null

**Comment by piotrdz** [comment]
I've never used ngcc, so I am not sure why this would happen.

I suppose it has to do with what happens behind the scenes in ng-packagr. I'll see if changing ng-packagr version fixes it.

**Comment by ThomasDevens** [comment]
FWIW this is still happening as of the latest version (2.0.3) and only seems to happen when running npm install after the initial install (npm install @angular-slider/ngx-slider@latest) (snippet for reference)
```
PS {path_to_project}> npm install

> icm@1.0.0 postinstall {path_to_project}
> ngcc

Compiling @angular-slider/ngx-slider : fesm2015 as esm2015
Compiling @angular-slider/ngx-slider : fesm5 as esm5
Compiling @angular-slider/ngx-slider : esm2015 as esm2015
Compiling @angular-slider/ngx-slider : esm5 as esm5
Compiling @angular-slider/ngx-slider : main as umd
Warning: Unable to fully load {path_to_project}/node_modules/@angular-slider/ngx-slider/bundles/angular-slider-ngx-slider.umd.js for source-map flattening: The "path" argument must be of type string. Received null
```

**Comment by ThomasDevens** [comment]
Started to get errors and warning after upgrading angular to 10/11/12:
```
Warning: Unable to fully load {path_to_project}/node_modules/@angular-slider/ngx-slider/bundles/angular-slider-ngx-slider.umd.js for source-map flattening: Cannot read property 'replace' of null
Warning: Unable to fully load {path_to_project}/node_modules/@angular-slider/ngx-slider/bundles/angular-slider-ngx-slider.umd.js for source-map flattening: Cannot read property 'replace' of null
Error: Error when flattening the source-map "{path_to_project}/node_modules/@angular-slider/ngx-slider/bundles/angular-slider-ngx-slider.umd.js.map" for "{path_to_project}/node_modules/@angular-slider/ngx-slider/bundles/angular-slider-ngx-slider.umd.js": TypeError: Cannot read property 'rawMap' of null
```

**Comment by ymoreau** [comment]
I have the same error logs as above with angular 13.

**Comment by roldengarm** [comment]
Yep, still the error `Error when flattening the source-map` on Angular 13. Is this being looked at?

**Comment by DzmVasileusky** [comment]
+1

**Comment by piotrdz** [comment]
Problems described here are no longer relevant in context of newer Angular versions. Therefore, closing this ticket.
