### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by inexuscore** [angular-slider/ngx-slider#224]
Hello,
I see that this repository was updated 15 days ago, is this actively maintained?
I'm using this library in several projects but unfortunately, I can't upgrade to Angular 11.
Any plans to update soon? There are forks on GitHub but I'd like to use the official repo.
Thanks a lot.

**Comment by Parsa-Sedigh** [comment]
Currently I'm using angular v11.0.4 and it works fine. What's your problem?

**Comment by inexuscore** [comment]
@Parsa-Sedigh I was able to upgrade to Angular 11.x without a problem, good to go for now.

**Comment by piotrdz** [comment]
Angular v11 is supported without problems in v2.0.0 through to v2.0.4.

Angular v12+ needs some changes to work properly, but there are other tickets open for it.

**Comment by inexuscore** [comment]
@piotrdz Excellent, I'm already using this in an Angular 13+ project, everything seems to be working fine but it would be great to get a round of decent updates.
