### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by AlexanderFSP** [angular-slider/ngx-slider#225]
Server side slider initialization throws a TypeError due to call of DOM API method.

![image](https://user-images.githubusercontent.com/30397060/100562353-84f07380-32cc-11eb-824a-1e41efaa11e7.png)

**Comment by Parsa-Sedigh** [comment]
I think you can use ifPlatformBrowser() to execute parts of code just in browser side. I'm using this package with angular 11.0.4 and universal and it has no problem

**Comment by floreauwe** [comment]
Hi ! I have the same problem and already tried with ifPlatformBrowser()

`ERROR TypeError: this.elemRef.nativeElement.getBoundingClientRect is not a function
    at SliderHandleDirective.getBoundingClientRect (E:\sites\project-d\dist\server\main.js:149256:43)
    at SliderHandleDirective.calculateDimension (E:\sites\project-d\dist\server\main.js:149228:26)`

**Comment by eufelipemateus** [comment]
Still have same problem here..

**Comment by piotrdz** [comment]
Closing as duplicate of #66. Angular universal compatibility is a known issue.

**Comment by techybolek** [comment]
Angular 18.0.2, ngx-slider 17.0.2, same problem after trying to add SSR.
