### ISSUE TITLE
Slider doesn't work properly when parent container is rotated

### ISSUE THREAD

**Issue by kfmorton** [angular-slider/ngx-slider#232]
Describe the bug
When the slider is embedded in a container (div) and the div is rotated 90 deg using CSS "transform: rotate(90deg);" the slider doesn't work. The behavior is broken, where it doesn't slide or move at all, and the labels are not aligned properly.

To Reproduce

Put the ng-slider in a div
Rotate the div using css 90 deg
The slider doesn't work, see issue
Expected behavior
The slider is supposed to work as normal

Screenshots

![image](https://user-images.githubusercontent.com/67749127/102927423-e1d7e780-448e-11eb-9ac4-45eae12e2f06.png)

CSS
.availability-edit-container {
-webkit-transform: rotate(90deg); /* Safari and Chrome /
-moz-transform: rotate(90deg); / Firefox /
-ms-transform: rotate(90deg); / IE 9 /
-o-transform: rotate(90deg); / Opera */
transform: rotate(90deg);
}

HTML

options are: draggableRange: true

I attempted to correct the issue. Let me know if this PR is headed in the right direction.
https://github.com/angular-slider/ngx-slider/pull/231

**Comment by piotrdz** [comment]
I merged the PR and this is now released in v2.0.4.
