### ISSUE TITLE
ERROR in Metadata version mismatch for module 

### ISSUE THREAD

**Issue by surajmdl** [angular-slider/ngx-slider#233]
Hello, 
I am getting this error while running 'ng serve' command. Please help me asap.

ERROR in Metadata version mismatch for module C:/Suraj/Project/CashFE/CashFE_22Dec2020/CashFE/WebApp/node_modules/@angular-slider/ngx-slider/angular-slider-ngx-slider.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Suraj/Project/CashFE/CashFE_22Dec2020/CashFE/WebApp/src/app/main/app.module.ts, resolving symbol AppModule in C:/Suraj/Project/CashFE/CashFE_22Dec2020/CashFE/WebApp/src/app/main/app.module.ts

**Comment by surajmdl** [comment]
See the below image. If I update the highlighted version to 3 from 4 then it is working fine for me.

![image](https://user-images.githubusercontent.com/11940579/103213222-0a4e5e80-4933-11eb-80bf-404afd61db93.png)

**Comment by piotrdz** [comment]
Closing old issues related to previous Angular versions. Newest release supports current Angular version (17) without issues.
