### ISSUE TITLE
CSS scaling of parent explodes ngx-slider

### ISSUE THREAD

**Issue by Bug-Reaper** [angular-slider/ngx-slider#234]
Great little library, it's a tragedy the vanilla mat-slider lacks many essential features. But this lib is feature rich, love the example documentation as well.

### Bug
A bug I stumbled into is that the slider breaks (displays wrong) if the `ngx-slider` element or any of it's parents contain a CSS scaling transform rule (Eg : `transform : scale(N) ;` ).

Steps to replicate:
1. Create a parent <div> to contain your slider and set the CSS rule `transform:scale(2);`.
2. Add an ngx-slider as a child to that parent <div>.
3. Load the page and attempt to slide the slider. 

Probably something to do with the process of setting hard CSS px offsets somewhere in the ngx-slider component.

### Semi-Workaround
You can counteract the parent scale with a rule on ngx-slider like this:
```
.parentContainingSlider
{
  transform:scale(2);
}

.yourNgxSlider{
  transform:scale(.5)
}
```
This workaround still left some undesirable behavior.

**Comment by wbtan7** [comment]
if you still need it, put the inverse scaling under the ngx-slider option, then it would works perfectly! Found it when going through option.ts

https://github.com/angular-slider/ngx-slider/blob/2b65d778346f1d49d15091a09e0da40242e8c8f6/src/ngx-slider/lib/options.ts#L216C22-L216C22

**Comment by Bug-Reaper** [comment]
Long escaped Angular stratosphere but really appreciate the heads up!

**Comment by wbtan7** [comment]
Was struggling to get it working for quite some time, comment here in case anyone else needs it as well haha

**Comment by piotrdz** [comment]
Closing as the workaround has been documented here.
