### ISSUE TITLE
hide ceil and floor value

### ISSUE THREAD

**Issue by CwjXFH** [angular-slider/ngx-slider#243]
Hi,
  I want to hide ceil and floor option values on-page, but I have not found how to set them.

![](https://user-images.githubusercontent.com/11468733/107731678-865d0400-6d31-11eb-978a-18bfcb5cf017.PNG)

**Comment by jacky-cmd** [comment]
what is the solution for this? I am facing same issue

**Comment by CwjXFH** [comment]
@jacky-cmd 
I use [@angular/material](https://material.angular.io/components/slider/overview) instead it.
