### ISSUE TITLE
Incorrect value selected when vertical scale does not fit on screen

### ISSUE THREAD

**Issue by johnpdev** [angular-slider/ngx-slider#246]
When a vertical scale does not fit in the viewport and there is a scrollbar, an incorrect value is selected when the slider is clicked. This occurs when **all** of the following are true:

- The vertical slider extends beyond the viewable area 
- The pointer is not visible on the screen
- The slider pointer is not focussed

If the slider pointer is focussed at the time the slider is clicked, then the correct value is selected. I have reproduced this using the vertical slider on your demo page so you should be able to do the same. The issue is more pronounced with larger scales of course, and the erroneous value selected is not constant (0 or 10 - low or high), it is offset from the point clicked. See the attached gif for an example, and please let me know if there is a configuration to get around this issue.

Thank you very much!

![vertical_scale_issue](https://user-images.githubusercontent.com/20425436/108381279-a7ac6d00-71d5-11eb-90c0-961a153912cb.gif)

**Comment by piotrdz** [comment]
There is a `scale` option provided in slider options to counteract CSS zoom effects. See #234 and #367. Closing this one as duplicate.
