### ISSUE TITLE
IONIC Android - Slider did't follow the touch slide

### ISSUE THREAD

**Issue by fabiookamura** [angular-slider/ngx-slider#256]
Hello,

I passing by issue when try to slide on IONIC 5 Android.

The "DOTS" only change when the focus came out from their.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/4563018/115906447-e95bcd00-a43d-11eb-8e2f-2f6767027737.gif)

**Comment by byoshinori** [comment]
Hi! I have the same problem here!

**Comment by JulioLodi** [comment]
same problem here.

**Comment by ViniciusTakeushi** [comment]
same problem here

**Comment by ThaddeeT** [comment]
Hello gentlemen,

Any news on this issue ?

**Comment by RajuDangol45** [comment]
Try detectChanges from ChangeDetectorRef until its fixed.

**Comment by shifenis** [comment]
> Try detectChanges from ChangeDetectorRef until its fixed.

@RajuDangol45  you mean `detectChanges` when the emitter emits the value? Can you provide some code? Thanks

**Comment by dolan-sentian** [comment]
Thanks @RajuDangol45 

I have used detectChanges on the userChange emitter and seems to be working alright:
**HTML:**
`<ngx-slider [(value)]="value" [options]="options" (userChange)="detectChanges()"></ngx-slider>`

**TS:**
```
public value: number = 50;
public options: Options = {
    floor: 0,
    ceil: 100,
};

constructor(private ref: ChangeDetectorRef) { }

detectChanges() {
    this.ref.detectChanges();
}
```

**Comment by ThaddeeT** [comment]
Thanks to @RajuDangol45 && @dolan-sentian, you made my day on this old issue that went under the carpet :) 

Cheers

**Comment by moataz-magdi-dm** [comment]
> Thanks @RajuDangol45
> 
> I have used detectChanges on the userChange emitter and seems to be working alright: **HTML:** `<ngx-slider [(value)]="value" [options]="options" (userChange)="detectChanges()"></ngx-slider>`
> 
> **TS:**
> 
> ```
> public value: number = 50;
> public options: Options = {
>     floor: 0,
>     ceil: 100,
> };
> 
> constructor(private ref: ChangeDetectorRef) { }
> 
> detectChanges() {
>     this.ref.detectChanges();
> }
> ```

you saved our life , thank you

**Comment by piotrdz** [comment]
Ionic is not officially supported. However, the workaround has been provided in comments above. Therefore, closing.
