### ISSUE TITLE
Upgrade to Angular 12

### ISSUE THREAD

**Issue by Tea-Ice** [angular-slider/ngx-slider#264]
This component gives peer dependency issues on Angular 12. Please update.

**Comment by mariyastash** [comment]
the same after upgrade to Angular 12

**Comment by EddieBenji** [comment]
is there a workaround for this?
thanks

**Comment by piotrdz** [comment]
Closing old issues on the topic of upgrades. Please follow discussion in more recent issues regarding this subject (#351, #355).
