### ISSUE TITLE
Slider doesn't scale with zoom css

### ISSUE THREAD

**Issue by varun-av** [angular-slider/ngx-slider#281]
Adding zoom to css breaks the slider. I have tried with [manualRefesh] but it doesn't work.
Please check it [here](https://ngx-slider-range-slider-example-usbkd2.stackblitz.io).

Tested in
- Safari: 14.0.3
- Chrome: 92.0.4515.159

**Comment by piotrdz** [comment]
There is a `scale` option provided in slider options to counteract CSS zoom effects. See #234 and #367. Closing this one as duplicate.
