### ISSUE TITLE
The handler doesn't move when multiple sliders are on screen

### ISSUE THREAD

**Issue by JoMas971** [angular-slider/ngx-slider#282]
It looks like there is a bug with the drag&drop feature when trying to move the handle manually. Clicking on the bar works, same with the ticks and with the keyboard, but when there is multiple sliders, the drag&move using the mouse seems to be blocked.

I'm on macOS 10.15 with latest Chrome and Firefox.

This is easy to reproduce, just go to [ngx-slider demo](https://angular-slider.github.io/ngx-slider/demos) and try to change the value of any sliders using the drag&move feature over the handle. You'll see that is somehow doesn't work.

Any ideas ?

**Comment by JoMas971** [comment]
I don't know why, but it looks like there is an issue with [throttleTime](https://www.learnrxjs.io/learn-rxjs/operators/filtering/throttletime#additional-resources) pipe within `event-listener-helper.ts` file. 
If i remove the whole pipe, it is working as expected.

**Comment by piotrdz** [comment]
I have removed throttling options in commit ec57026. They were not working quite as well as I expected, and there are some differences between browsers, making them unreliable.

**Comment by piotrdz** [comment]
This should be fixed now in v2.0.4.
