### ISSUE TITLE
Can't drag slider

### ISSUE THREAD

**Issue by matteopasqualin** [angular-slider/ngx-slider#283]
Hello, both in home page and demos page I can't drag the pointer but only click to move it. Is it normal?
Same behavior with Chrome and Firefox Developer.
In Safari I can drag the pointer but some strange vertical lines appear on the slider.

**Comment by JoMas971** [comment]
Hi, I have made a ticket for the same issue (#282). But it seems that the whole event handler logic of this project is really not ideal. Like i've explained in my ticket, the events are not well handled. I guess, it would have been better to use the ngZone to run those handler outside andular.

Also, it seems this project is abandoned (nothing has been released within 10 months) and the tickets list is growing day after day... I've personally decided to not use this library and instead create my own by forking the angular material one. A lot of cool features that offer this ngx-slider library is not present in the material lib, but the events are handled in a  much better way. There is less events, and less memory consumption. Just a bit more work to have the same features...

Anyway, good luck!

**Comment by matteopasqualin** [comment]
I see, thanks JoMas971. Yep, it' better if they close the project

**Comment by nikita-fuchs** [comment]
bump.

too bad, why can't we have decent sliders for angular ? :/

**Comment by piotrdz** [comment]
This should be fixed now in v2.0.4.
