### ISSUE TITLE
Dead library?

### ISSUE THREAD

**Issue by uberspeck** [angular-slider/ngx-slider#306]
No updates for ~15 months and 2 versions behind on Angular. Looks like radio silence on issues from maintainers as well?

Anyone know if this library is officially "dead"?

**Comment by piotrdz** [comment]
When I started this project, I thought it would be used at the place I worked at, so I would be able to officially support it, and even get paid for it. I thought I could extend it and work on some new features.

But funny how life works, none of the above happened. I never got to use the slider, even in a personal project.

I ended up maintaining it for a while, but you can see that this is like taking on another job to keep up with everything. Last two years have been difficult for me, even with my regular job. So yes, as things stand today, the project ended up dead in the sense that I do not see myself maintaining it further.

In the next few days, I will do a few last things on the project to get some outstanding merge requests merged in and resolve Angular version compatibility, but after that I will post the update about the project not being maintained further. @uberspeck  You or anyone else will be welcome to volunteer to become the new maintainer.

**Comment by uberspeck** [comment]
@piotrdz no judgement here. I understand completely! I would love to take it over but, like you, I don't have the resources to make that happen. FWIW, I hope you don't feel you owe anyone anything. Thank you for creating a great library that we have been able to depend on for years 😀

**Comment by malarahfelipe** [comment]
Thanks for the effort @piotrdz 👏

**Comment by piotrdz** [comment]
Closing old issues about the same subjects. Please follow discussion in more recent issues regarding this subject (#351, #355).
