### ISSUE TITLE
 Incorrect slider behavior

### ISSUE THREAD

**Issue by novakand** [angular-slider/ngx-slider#316]
Incorrect slider behavior
The slider starts to move spontaneously, what could be the reason for this? Thanks!
http://g.recordit.co/wQj4jiZrLs.gif

**Comment by novakand** [comment]
https://stackblitz.com/edit/angular-9-google-maps-msebyl?file=src%2Fapp%2Fapp.component.html 
If you sharply pull the slider and without releasing (mouse button) go to another element (document) or out of the field of view, the element jerks

**Comment by novakand** [comment]
<img width="926" alt="image" src="https://user-images.githubusercontent.com/45287302/160269298-0088c125-f85b-4927-8ff4-a3b92f6e83d1.png">
Click marker, show InfoBox

**Comment by novakand** [comment]
apparently the event that the slider was released does not fire

**Comment by novakand** [comment]
Incorrect behavior observed in version 2.0.4

https://stackblitz.com/edit/angular-9-google-maps-laxade?file=src%2Fapp%2Fapp.component.ts

**Comment by mauro-montano** [comment]
Is there some solution? I have this problem that comes from the library

![ngxslider bug](https://user-images.githubusercontent.com/112961400/222430760-2796ec29-2fbf-4b61-8e5c-11b085ec6cda.gif)

**Comment by piotrdz** [comment]
I haven't observed any such behaviour since fixing #366. I'm going to close this one.
