### ISSUE TITLE
0 is showed incorrect format: 1.7763568394e-15

### ISSUE THREAD

**Issue by MartinMilata** [angular-slider/ngx-slider#317]
https://angular-slider.github.io/ngx-slider/demos#selection-bar-from-value-slider
use these values:
export class AppComponent {
  value: number = 0;
  options: Options = {
    floor: -10.1,
    ceil: 10.1,
    step: 0.1
  };
}
![image](https://user-images.githubusercontent.com/79250857/160347461-3c736c78-5dcb-4199-b829-2675fb98e7f2.png)

**Comment by piotrdz** [comment]
This can be fixed using `precisionLimit` option, which controls the precision of formatted numbers that slider displays.

This works well for the example given:
```
  options: Options = {
    floor: -10.1,
    ceil: 10.1,
    step: 0.1,
    precisionLimit: 2
  };
```
