### ISSUE TITLE
Ceil and Floor values disappears on sliding to extreme ends

### ISSUE THREAD

**Issue by ridhi58** [angular-slider/ngx-slider#320]
When i try to slide the value to the extreme right or left , the ceil and the floor labels disappears. How do i prevent them from disappearing?

**Comment by brhernandez** [comment]
In options you can set the property autoHideLimitLabels to false, like is shown below
 options: Options = {
    autoHideLimitLabels: false
}
Hope this helps

**Comment by piotrdz** [comment]
Closing as the solution is in comment above.
