### ISSUE TITLE
Slider with Ionic won't update

### ISSUE THREAD

**Issue by shifenis** [angular-slider/ngx-slider#321]
Using the slider with the Ionic framework on the mobile device, the value is updated but the handler isn't updated.
I tried to stimulate the detection changes on the `valueChange` output.

Any idea about losing focus or anything like that?

**Comment by ThaddeeT** [comment]
Hey man, https://github.com/angular-slider/ngx-slider/issues/256 !

Have a great day !

**Comment by piotrdz** [comment]
Closing as duplicate of #256.
