### ISSUE TITLE
ngx-slider is not compatible with the default, recommended content-security-policy

### ISSUE THREAD

**Issue by roldengarm** [angular-slider/ngx-slider#324]
I've configured the recommended content-security-policy, and then I'm getting this error:

Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.

![image](https://user-images.githubusercontent.com/37638588/172290176-08d68643-cd03-4fe2-a0de-468f91d1d458.png)
![image](https://user-images.githubusercontent.com/37638588/172290311-1fbdef0d-8105-405f-bcab-275d77fa294a.png)

Our CSP is configured as [per Angular's recommendation](https://angular.io/guide/security#enforcing-trusted-types):

```
trusted-types angular angular#bundler; require-trusted-types-for 'script'; default-src 'self'; script-src 'self' 'unsafe-hashes' 'sha256-MhtPZXr7+LpJUY5qtMutB+qWfQtMaPccfe7QXtCcEYc='; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; object-src 'none'; base-uri 'self'; connect-src 'self'; font-src 'self' https://fonts.gstatic.com; frame-src 'self' ; img-src 'self' blob: data:; manifest-src 'self'; media-src 'self'; frame-ancestors 'none'; form-action 'self
```
Even adding `angular#unsafe-bypass` as trusted-type doesn't work. This is a security concern

**Comment by piotrdz** [comment]
This has been solved by adding AllowUnsafeHtmlInLabels option in v17.0.0. Closing.
