### ISSUE TITLE
Error while giving npm i

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular-slider/ngx-slider#325]
While giving `npm i` it thorws below error

![image](https://user-images.githubusercontent.com/36756050/174787434-29a5b0d7-02ad-4995-a7fb-b245e3f2862a.png)

it because of 

https://github.com/angular-slider/ngx-slider/blob/master/package.json#L40

**Comment by piotrdz** [comment]
Closing old issues related to previous Angular versions. Most recent release supports current Angular version (17) without issues.
