### ISSUE TITLE
Not compatible Ivy compiler

### ISSUE THREAD

**Issue by nen155** [angular-slider/ngx-slider#327]
Angular version: **14.0.4**
**angular.json** 
{
   "projects": {
      "my-existing-project": {
         "architect": {

            "build": {
               "options": {
                  ...
                  "aot": true,
               }
            }
         }
      }
   }
}
**tsconfig.app.json** 
{ 
   ... 
   "angularCompilerOptions": { 
      "enableIvy": true 
}

Cannot use this module not compatible with Ivy compiller.

If you remove ivy compiler from tsconfig and angular.json works, but before you must to remove node_modules folder and after you need to do npm install.

**Comment by mokipedia** [comment]
If you are using angular 14, ivy is already the default, no need to add "enabeIvy" in compiler options. Also, ngcc will convert this module to ivy and this works well.
So if ngcc compiling breaks for you, the problem probably is in your settings.

that being said, it would be nice to see this project updated to ivy native in the future ^^

**Comment by narendrasinghrathore** [comment]
'NgxSliderModule' does not appear to be an NgModule class.

This likely means that the library (@angular-slider/ngx-slider) which declares NgxSliderModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by sovushka-utrom** [comment]
I get the same message as @narendrasinghrathore

**Comment by narendrasinghrathore** [comment]
⠹ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- @angular-slider/ngx-slider [es2015/esm2015] (https://github.com/angular-slider/ngx-slider.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by thanhlt90** [comment]
Hi,
I got the same issue with @narendrasinghrathore . Any solution to resolve it with new Angular Ivy version, please ?

**Comment by pumano** [comment]
@thanhlt90 only possible way is not use this library, because this library is abandoned

**Comment by narendrasinghrathore** [comment]
> Hi, I got the same issue with @narendrasinghrathore . Any solution to resolve it with new Angular Ivy version, please ?

@thanhlt90 try to rebuild or do `npm install` again after adding library, maybe it will resolve.

**Comment by thanhlt90** [comment]
> > Hi, I got the same issue with @narendrasinghrathore . Any solution to resolve it with new Angular Ivy version, please ?
> 
> @thanhlt90 try to rebuild or do `npm install` again after adding library, maybe it will resolve.

Yeah! It's working for me when try to rebuild with ngcc. Thanks @narendrasinghrathore!

**Comment by danisss9** [comment]
check #296

**Comment by whyboris** [comment]
Looking at #296 - there is an alternative:

https://github.com/danisss9/ngx-slider 🤝 https://www.npmjs.com/package/ngx-slider-v2

Same as this repository, but install with `npm install --save ngx-slider-v2` and then change the import to:

```ts
import { NgxSliderModule } from 'ngx-slider-v2';
```

**Comment by poriakahrizi** [comment]
first npm install --save @angular-slider/ngx-slider and this not work and has error
but 
npm install --save ngx-slider-v2
this work
thank for this npm install --save ngx-slider-v2

**Comment by poriakahrizi** [comment]
If you encounter CUSTOM_ELEMENTS_SCHEMA error in the module you use this package
  schemas: [ CUSTOM_ELEMENTS_SCHEMA , NO_ERRORS_SCHEMA]
Add after the declarations

**Comment by piotrdz** [comment]
Closing old issues on the topic of upgrades. Please follow discussion in more recent issues regarding this subject (#351, #355).
