### ISSUE TITLE
Not compatible with Angular Ivy

### ISSUE THREAD

**Issue by SagarStake** [angular-slider/ngx-slider#333]
Im trying to use the library with Angular 14, when I import the module in my module imports, angular is complaining that it is not an Ivy compatible version.

`NgxSlider module

The module exports the slider component

'NgxSliderModule' does not appear to be an NgModule class.(-996002)
slider.module.d.ts(2, 25): This likely means that the library (@angular-slider/ngx-slider) which declares NgxSliderModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

Any solution or work around to solve this issue?

**Comment by Ryders** [comment]
Have you considered doing a quick search to avoid creating noise?

https://github.com/angular-slider/ngx-slider/issues/327

**Comment by najeem99** [comment]
> Have you considered doing a quick search to avoid creating noise?
> 
> #327

yes it is not compatible

**Comment by danisss9** [comment]
check #296

**Comment by whyboris** [comment]
✅  confirming that [danisss9/ngx-slider](https://github.com/danisss9/ngx-slider) _Fork_ works with Angular 16 🚀

**Comment by Rituraj-Das** [comment]
node_modules/ng2-order-pipe/dist/src/ng2-order.module.d.ts:1:22
    1 export declare class Ng2OrderModule {
                           ~~~~~~~~~~~~~~
    This likely means that the library (ng2-order-pipe) which declares Ng2OrderModule is not compatible with Angular Ivy. Check 
if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by mqJose** [comment]
'NgxPopperModule' does not appear to be an NgModule class.(-996002)

popper.module.d.ts(3, 18): This likely means that the library (ngx-popper) which declares NgxPopperModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by Muzummil** [comment]
+1
'PlyrModule' does not appear to be an NgModule class.(-996002)
plyr.module.d.ts(1, 22): This likely means that the library (ngx-plyr) which declares PlyrModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by siva2126** [comment]
'NgxPopperModule' does not appear to be an NgModule class.(-996002)
popper.module.d.ts(4, 28): This likely means that the library (ngx-popper) which declares NgxPopperModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

did anyone know how to solve this
