### ISSUE TITLE
Horizontal Slider goes crazy up and down without stopping in 2.0.4. version

### ISSUE THREAD

**Issue by Simonioa** [angular-slider/ngx-slider#335]
Hello i am using ngx slider 

`	<ngx-slider [(ngModel)]="my_pointsNew" (userChange)="onUserChange($event)" [(value)]="verticalSlider3.my_pointsNew" 
										[options]="verticalSlider3.options">
									</ngx-slider>`

and the slider doesnt stop to move after i try to set a value. It goes up and down without stopping. I see that happens in others too but with no solution. Any ideas?

**Comment by Simonioa** [comment]
![Nov-15-2022 22-45-59](https://user-images.githubusercontent.com/15795238/202021918-ad84238f-b2fb-4cdc-a14c-79b9a850a1fc.gif)

**Comment by ia-anket** [comment]
@Simonioa  Did you find any workaround or fix for this?

**Comment by Simonioa** [comment]
No I haven't wating for a new version, but i downgraded to lower version. It doesn't work perfectly but at least it diesn't do what i showed in the gif

**Comment by mauro-montano** [comment]
Is there some solution? I have this problem that comes from the library

![ngxslider bug](https://user-images.githubusercontent.com/112961400/222430760-2796ec29-2fbf-4b61-8e5c-11b085ec6cda.gif)

**Comment by Simonioa** [comment]
No i havent found a solution. Downgrade to first version 2.0.1 to see how it works for you
________________________________

**Comment by piotrdz** [comment]
As in #316, I haven't observed any such in recent versions, especially since fixing #366. I'm going to close this one.
