### ISSUE TITLE
Problem when min value = max value

### ISSUE THREAD

**Issue by andrei4ik1997** [angular-slider/ngx-slider#348]
How can I solve the problem when min value = max value . So that the min pointer is located on the left and the max pointer is located on the right (screen 2)
![1](https://user-images.githubusercontent.com/89358142/220348538-b82d2373-5baa-4fb5-a4a7-f21520849207.png)
![2](https://user-images.githubusercontent.com/89358142/220348541-f1d75852-b73f-415c-ad99-3eed582ebf3f.png)

**Comment by andrei4ik1997** [comment]
The problem was solved by adding styles:
.ngx-slider-pointer-max {
	right: 0;
}
.ngx-slider-pointer-min {
	left: 0;
}

**Comment by ui-jb** [comment]
I have this issue when the min and max are the same and the slider is initially hidden. Changing the styles mentioned above and using manualRefresh doesn't work.

**Comment by piotrdz** [comment]
Closing as won't fix. Min value = max value is an edge case that I don't have plans to support.
