### ISSUE TITLE
ngx-slider is not working for float values

### ISSUE THREAD

**Issue by Ashu2398** [angular-slider/ngx-slider#350]
I tried with float values between 0 to 1 but the slider is not working

tested code-
 value: number = 0.04;
  highValue: number = 0.5;
  options: Options = {
    floor: 0.04,
    ceil: 0.5
  };

![image](https://user-images.githubusercontent.com/125260099/223101225-76fea576-7af1-496b-93a8-e00928c8085f.png)

**Comment by Ashu2398** [comment]
Found some solution for this issue.

**Comment by b09h** [comment]
using step as 0.001 key inside options key. Refer Official documentation for this
