### ISSUE TITLE
On a scale from 1 to 10, 5 is not halfway

### ISSUE THREAD

**Issue by unrealxqt** [angular-slider/ngx-slider#353]
![image](https://github.com/angular-slider/ngx-slider/assets/20015173/edece5d8-7292-4579-b62c-85fff544802b)

We can clearly see that 5 is not exactly halfway of the slider.

I can't find what causes this.
Do you have any ideas how I could place the 5 exactly at halfway of the slider?

**Comment by BojanKogoj** [comment]
There are 3 numbers between 1-5, and 4 between 5-10, and all numbers are spaced evenly.

**Comment by piotrdz** [comment]
Closing as explained, it is not a defect.
