### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by praveen-angular** [angular-slider/ngx-slider#354]
Please provide support to angular 16.

This likely means that the library (@angular-slider/ngx-slider) which declares NgxSliderModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by roopeshreddy** [comment]
Hey, this is not upgraded for quite some time. One of the community member forked this branch and upgraded to few Angular versions. Please check - [https://www.npmjs.com/package/ngx-slider-v2](https://www.npmjs.com/package/ngx-slider-v2)

**Comment by praveen-angular** [comment]
Thank you very much it is working
