### ISSUE TITLE
Misalignment in horizontal slider due to improper scss code

### ISSUE THREAD

**Issue by VicM** [angular-slider/ngx-slider#356]
The default styles create a improper alignment in a single slider, the left side of the slider does not have padding and the right one have more, when moving the handle to the ticks the handle does not center on the tick mark.

the problem is the following line of the ngx-slider.scss file
`
.ngx-slider-tick {
...
   margin-left: math.div($handleSize, 2) - math-div($ticksWidth, 2);
...
}
`

the line must be as follow (math point div, instead of math bar div)
`margin-left: math.div($handleSize, 2) - math.div($ticksWidth, 2);`

Fixing that fixes the alignment.

**Comment by piotrdz** [comment]
Fixed and released in v17.0.0.
