### ISSUE TITLE
Bad performance with huge ceil value

### ISSUE THREAD

**Issue by danisss9** [angular-slider/ngx-slider#366]
Hey there! Thanks a lot for forking the project. 🚀

We use the slider in our application to let the user select one of 86400 seconds and with ceil values that large, the browser needs to work for a long time before it displays the page. It used to work with the original implementation.

Repro:
<ngx-slider [options]="{ ceil: 86400 }"></ngx-slider>

https://stackblitz.com/edit/angular-74vxas?file=src/main.ts

**Comment by danisss9** [comment]
Important findings:

> We had the same issue and the high `ceil` value does not seem to be the problem but the large number of steps. So a workaround might be to increase the `step` value in the options if you have a large difference between `floor` and `ceil`.
> 
> In our case we had a logarithmic scale, so setting a high `step` value was not desirable on the low end of the slider. Instead we set the `stepsArray` option instead of `floor`, `ceil` and `step` and computed the logarithmic steps ourselves. For up to a few hundred steps the performance of the slider seems to be okay.

And:

> This turns out to be due to the large number of ticks and change detection. When a large number of ticks is added to `this.ticks`, the change detector appears to run through all of the values. To avoid this behavior and not show any ticks, simply add `ticksArray: []` to the options object. The ticks array is generated even when `showTicks: false` is configured, so this appears to be the best way to make the component faster.
> 
> Working demo with a minimum of 0, maximum of 6,000,000, and the ticks are overridden with an empty array: https://codesandbox.io/p/sandbox/hardcore-haze-46cgft?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A1%2C1
> 
> The problem we had with mat-slider is that it did not update fast enough, so moving the handle with an average mouse speed caused it to not update. Also, accidentally leaving the track vertically and letting go caused weird issues if you drag the mouse over the handles again. Thus, no mat-slider for us.

**Comment by Kaizodo** [comment]
Yup i confirm that my max sail value is 200000 and browser seems to freez on large values

**Comment by shreekannan** [comment]
@piotrdz  do know when it will be released ?

**Comment by shreekannan** [comment]
@piotrdz  do you know when it will be released ?

**Comment by piotrdz** [comment]
I was adding some more e2e tests and testing on mobile. It is done now.

The fix is released in v15.0.1 / v16.0.1 / v17.0.2.

Closing.
