### ISSUE TITLE
Backports for previous Angular versions

### ISSUE THREAD

**Issue by piotrdz** [angular-slider/ngx-slider#368]
Following the upgrade to Angular 17, the backports for previous Angular versions should also be released in the official package. This issue is raised to keep track of this work.

Checklist:
- [x] backport for Angular 13
- [x] backport for Angular 14
- [x] backport for Angular 15
- [x] backport for Angular 16

**Comment by piotrdz** [comment]
@amelnikoff It was supposed to be a temporary state after merging Angular 17 support from forked repository.

I should have v15 released by the end of this week.

**Comment by piotrdz** [comment]
@amelnikoff And there you go, I just released v15 backport. It turned out to be much easier than I thought.

**Comment by amelnikoff** [comment]
@piotrdz cool, it works fine! Thanks!

**Comment by AbhishekSI-UK** [comment]
This slider will support for Angular 11

**Comment by piotrdz** [comment]
@AbhishekSI-UK Angular 11 has been supported all along with previous version of the slider (v2.0.4).

**Comment by piotrdz** [comment]
All backports are finished now, and I updated the table with version dependencies in README. There is now support for every Angular version from 6 to 17 across old releases, backports and the current master targeting v17.

**Comment by AbhishekSI-UK** [comment]
> @AbhishekSI-UK Angular 11 has been supported all along with previous version of the slider (v2.0.4).

Thax for update.
