### ISSUE TITLE
Discord invitation link in README is not working

### ISSUE THREAD

**Issue by vinlos** [angular-slider/ngx-slider#369]
Hello,

I tried to join Discord link but invitations seems invalid or expired. May you please fix this?

![image](https://github.com/angular-slider/ngx-slider/assets/1380443/842a243a-8ab4-4c5f-965f-705ce7bcb2a8)

https://discord.gg/C6K9S9r7

**Comment by piotrdz** [comment]
Sorry about that. I thought I set that link to never expire but apparently it did expire.

The new one is: https://discord.gg/DSey8F96 and I will update it in README in a moment.

**Comment by piotrdz** [comment]
Link is fixed in README and I also published amended NPM package v17.0.1 so it is also fixed on npmjs.org.
