### ISSUE TITLE
angular 17.3.5 => ERESOLVE could not resolve

### ISSUE THREAD

**Issue by StanAmaris** [angular-slider/ngx-slider#376]
While installing the lib on an angular 17.3.5, i get an error that it cannot resolve some dependencies, it is looking for 17.1.1 and not 17.3.5 or over. I need to install the lib with --force, which causes problemes with my deployment pipeline. Would it be possible to update de thependencies to allow those in my error message or later ? 

Thank you.
(PS: Thanks for that lib, the slider is very cool and customizable, it is always my go to when in need of a slider :D )

`
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular-slider/ngx-slider@17.0.2
npm ERR! Found: @angular/common@17.0.8
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^17.0.0" from the root project
npm ERR!   peer @angular/common@"^17.0.0" from @amaris/lib-highway@0.1.23
npm ERR!   node_modules/@amaris/lib-highway
npm ERR!     @amaris/lib-highway@"^0.1.23" from the root project
npm ERR!   9 more (@angular/cdk, @angular/platform-browser, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.1.1" from @angular-slider/ngx-slider@17.0.2
npm ERR! node_modules/@angular-slider/ngx-slider
npm ERR!   @angular-slider/ngx-slider@"^17.0.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/common@17.3.5
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^17.1.1" from @angular-slider/ngx-slider@17.0.2
npm ERR!   node_modules/@angular-slider/ngx-slider
npm ERR!     @angular-slider/ngx-slider@"^17.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by danisss9** [comment]
Try deleting the **node_modules** and **package-lock.json** and then `npm install`

The lib peerDeps is ["^17.1.1"](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept) so it should work with angular 17.3.5.

**Comment by piotrdz** [comment]
I confirmed that the slider is working in a fresh Angular project created for Angular = 17.3.5. As explained above, this issue is caused by corrupted `package-lock.json` or `node_modules/`, not any dependency setting of ngx-slider.
