### ISSUE TITLE
Angular 18 support

### ISSUE THREAD

**Issue by nick-goloborodko** [angular-slider/ngx-slider#379]
I'm about to kick off a new project based on Angular 18 that I was hoping to use ngx-slider. The current version does not appear to be compatible with Angular 18.

Is there any planned support for angular 18 and any timeframes?

**Comment by srikanthonl** [comment]
Yes, Angular 18 support please.

**Comment by dnlrbz** [comment]
@piotrdz could you please upgrade to Angular 18?

**Comment by lampewebdev** [comment]
> @piotrdz could you please upgrade to Angular 18? UPD: There is a related issue in bootstrap (necessary for upgrade of ngx-slider): [ng-bootstrap/ng-bootstrap#4703](https://github.com/ng-bootstrap/ng-bootstrap/issues/4703)

Bootstrap has released a version for angular 18.

When can we think of getting an update to angular 18?

**Comment by srikanthonl** [comment]
Any update on this please?

**Comment by piotrdz** [comment]
I don't have much time these days to work on this project but I'll see what I can do later this week.

**Comment by cgo123** [comment]
Please update

**Comment by piotrdz** [comment]
Angular 18 update has been completed and released in v18.0.0.

**Comment by srikanthonl** [comment]
> Angular 18 update has been completed and released in v18.0.0.

Wonderful. Thanks @piotrdz
