### ISSUE TITLE
It is possible to make an overflow ?

### ISSUE THREAD

**Issue by mitch85** [angular-slider/ngx-slider#94]
Hi,
i want to use the slider as Timerpicker.. with two values
(START 00:00)-------- ON TIME _______________ OFF TIME-------------(END 24:00)

But i need also to put a ON TIME for example 23:00 and the OFF TIME AT 04:00
(START 00:00)___________ OFF TIME ---------------- ON TIME ___________ (END 24:00)

is something like this possible?

**Comment by piotrdz** [comment]
Sorry for late reply. Currently, the slider has a concept of low and high slider handles and it always tries to maintain the invariant: `floor <= low handle value <= high handle value <= ceil`. So you can't slide the high handle past the low handle.

I might add this functionality at some point, but at the moment, I would like to focus on other priority issue. This change would require overwriting a lot of internal logic in the slider.

In the meantime, as a workaround, you could provide a custom translate function and try to track which handle is on time and which is off time in some way.

**Comment by piotrdz** [comment]
In the future, I plan to implement something like this in #115 - it will be possible to add two or more generic handles which will not have range constraints. It would achieve the result that is needed here.

I will close this in favour of future work in #115.
